import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { ContentBrief } from "@/lib/types";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#171717" },
  title: { fontSize: 18, fontWeight: 700, marginBottom: 4 },
  subtitle: { fontSize: 9, color: "#666666", marginBottom: 16 },
  notesBox: {
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
    borderRadius: 4,
    padding: 10,
    marginBottom: 16,
  },
  notesHeading: { fontSize: 9, fontWeight: 700, marginBottom: 4, textTransform: "uppercase", color: "#1e3a8a" },
  note: { fontSize: 9, color: "#1e3a8a", marginBottom: 2 },
  section: { marginBottom: 14 },
  sectionHeading: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
    color: "#666666",
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5e5",
    paddingBottom: 3,
  },
  paragraph: { lineHeight: 1.5, marginBottom: 4 },
  bullet: { flexDirection: "row", marginBottom: 3, alignItems: "flex-start" },
  bulletMarker: { width: 10 },
  bulletText: { flex: 1, lineHeight: 1.4 },
  label: { fontWeight: 700 },
  outlineItem: { flexDirection: "row", marginBottom: 4, alignItems: "flex-start" },
  outlineTag: {
    fontSize: 7,
    fontWeight: 700,
    backgroundColor: "#f0f0f0",
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginRight: 6,
    borderRadius: 2,
  },
  needsSourceTag: {
    fontSize: 7,
    fontWeight: 700,
    backgroundColor: "#fef3c7",
    color: "#92400e",
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginRight: 6,
    borderRadius: 2,
  },
});

function Bullet({ children }: { children: React.ReactNode }) {
  return (
    <View style={styles.bullet}>
      <Text style={styles.bulletMarker}>{"•"}</Text>
      <Text style={styles.bulletText}>{children}</Text>
    </View>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section} wrap={false}>
      <Text style={styles.sectionHeading}>{title}</Text>
      {children}
    </View>
  );
}

export function BriefPdfDocument({ brief }: { brief: ContentBrief }) {
  return (
    <Document title={`Content Brief - ${brief.topic}`}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Content Brief: {brief.topic}</Text>
        <Text style={styles.subtitle}>Generated by Content Brief Generator</Text>

        {brief.groundingNotes.length > 0 ? (
          <View style={styles.notesBox}>
            <Text style={styles.notesHeading}>Data sources for this brief</Text>
            {brief.groundingNotes.map((note, i) => (
              <Text key={i} style={styles.note}>
                {"•"} {note}
              </Text>
            ))}
          </View>
        ) : null}

        <Section title="Summary / TL;DR">
          <Text style={styles.paragraph}>{brief.summary}</Text>
        </Section>

        <Section title="Target keyword + related terms">
          <Text style={styles.paragraph}>
            <Text style={styles.label}>Primary: </Text>
            {brief.keywords.primary}
          </Text>
          {brief.keywords.secondary.map((term) => (
            <Bullet key={term}>{term}</Bullet>
          ))}
        </Section>

        <Section title="Search intent">
          <Text style={styles.paragraph}>
            <Text style={styles.label}>Type: </Text>
            {brief.searchIntent.type}
          </Text>
          <Text style={styles.paragraph}>
            <Text style={styles.label}>Job to be done: </Text>
            {brief.searchIntent.job}
          </Text>
        </Section>

        <Section title="Recommended title options">
          {brief.titleOptions.map((title, i) => (
            <Bullet key={title}>
              {i + 1}. {title}
            </Bullet>
          ))}
        </Section>

        <Section title="Content outline">
          {brief.outline.map((item, i) => (
            <View key={i} style={[styles.outlineItem, item.level === "H3" ? { marginLeft: 16 } : {}]}>
              <Text style={styles.outlineTag}>{item.level}</Text>
              <Text style={styles.bulletText}>
                <Text style={styles.label}>{item.heading}</Text> — {item.note}
              </Text>
            </View>
          ))}
        </Section>

        <Section title="Word count target">
          <Text style={styles.paragraph}>
            <Text style={styles.label}>Total: </Text>~{brief.wordCount.total.toLocaleString("en-US")} words
          </Text>
          {brief.wordCount.sections.map((s) => (
            <Bullet key={s.section}>
              {s.section}: ~{s.words} words
            </Bullet>
          ))}
        </Section>

        <Section title="Template recommendation">
          <Text style={styles.paragraph}>
            <Text style={styles.label}>{brief.template.recommendation}</Text>
          </Text>
          <Text style={styles.paragraph}>{brief.template.reason}</Text>
        </Section>

        <Section title="Competitive gap notes">
          {brief.competitiveGaps.map((gap, i) => (
            <Bullet key={i}>{gap}</Bullet>
          ))}
        </Section>

        <Section title="Statistics / evidence checklist">
          {brief.statsChecklist.map((item, i) => (
            <View key={i} style={styles.bullet}>
              <Text style={styles.needsSourceTag}>needs source</Text>
              <Text style={styles.bulletText}>{item.claim}</Text>
            </View>
          ))}
        </Section>

        <Section title="Image / chart suggestions">
          {brief.visualSuggestions.map((v, i) => (
            <Bullet key={i}>
              <Text style={styles.label}>{v.placement}: </Text>
              {v.description}
            </Bullet>
          ))}
        </Section>

        <Section title="Internal linking suggestions">
          {brief.internalLinks.suggestions.map((s, i) => (
            <Bullet key={i}>
              <Text style={styles.label}>{s.anchorText}: </Text>
              {s.note}
            </Bullet>
          ))}
          <Text style={[styles.paragraph, { color: "#666666", fontSize: 9 }]}>{brief.internalLinks.note}</Text>
        </Section>

        <Section title="FAQ candidates">
          {brief.faqs.map((faq) => (
            <Bullet key={faq}>{faq}</Bullet>
          ))}
        </Section>

        <Section title="Distribution notes">
          {brief.distributionNotes.map((note, i) => (
            <Bullet key={i}>{note}</Bullet>
          ))}
        </Section>

        <Section title="NotebookLM Research Kit">
          <Text style={[styles.paragraph, styles.label]}>Suggested sources to add</Text>
          {brief.notebookLmResearchKit.suggestedSources.map((source, i) => (
            <Bullet key={i}>{source}</Bullet>
          ))}
          <Text style={[styles.paragraph, styles.label, { marginTop: 6 }]}>Suggested questions to ask</Text>
          {brief.notebookLmResearchKit.suggestedQuestions.map((question, i) => (
            <Bullet key={i}>{question}</Bullet>
          ))}
        </Section>
      </Page>
    </Document>
  );
}
